language: node_js # 声明环境为node
node_js: stable

# sudo: required

# Travis-CI Caching
cache:
  directories:
    - node_modules # 缓存node_modules文件夹

# S: Build Lifecycle
install:
  - npm install # 下载依赖

before_script:


script: 
  - hexo clean && hexo g

  - cd ./public
  - git init
  - git config --global user.name "yolayolayolanda"
  - git config --global user.email "yolayolayolanda@foxmail.com"
  - git add .
  - git commit -m "Travis build blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source # 只对 source 分支构建
env: # 环境变量
 global:
   - GH_REF: github.com/yolayolayolanda/yolayolayolanda.github.io.git # github 仓库地址

